import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common'; import { AvailabilityStatus, BookingStatus, Prisma, ServiceStatus, SlotStatus } from '@prisma/client'; import { PrismaService } from '../../database/prisma.service'; import * as crypto from 'crypto';
type BulkAvailabilityInput={serviceId:string;startDate:string;endDate:string;weekdays:number[];startTime:string;endTime:string;slotDuration:number;capacity:number;publish:boolean};
const transactionOptions={maxWait:10000,timeout:20000};
@Injectable() export class SchedulingService {constructor(private db:PrismaService){}
 async services(){return this.db.service.findMany({where:{status:'ACTIVE'},orderBy:{name:'asc'}})}
 async adminServices(){return this.db.service.findMany({where:{status:{not:ServiceStatus.ARCHIVED}},orderBy:{name:'asc'}})}
 async createService(input:{name:string;description:string;durationMinutes:number;priceMinor:number;status?:ServiceStatus}) { return this.db.service.create({data:{...input,status:input.status ?? ServiceStatus.ACTIVE}}) }
 async updateService(id:string,input:{name?:string;description?:string;durationMinutes?:number;priceMinor?:number;status?:ServiceStatus}) { const found=await this.db.service.findUnique({where:{id}});if(!found)throw new NotFoundException('Service not found');return this.db.service.update({where:{id},data:input}) }
 async archiveService(id:string) { const found=await this.db.service.findUnique({where:{id}});if(!found)throw new NotFoundException('Service not found');return this.db.service.update({where:{id},data:{status:ServiceStatus.ARCHIVED}}) }
 async dates(serviceId:string){const now=new Date();const slots=await this.db.timeSlot.findMany({where:{serviceId,status:SlotStatus.ACTIVE,service:{status:'ACTIVE'},availability:{status:AvailabilityStatus.PUBLISHED},startAt:{gt:now}},select:{date:true,bookedCount:true,capacity:true},orderBy:{date:'asc'}});return [...new Map(slots.filter(s=>s.bookedCount<s.capacity).map(s=>[s.date.toISOString().slice(0,10),{date:s.date}])).values()]}
 async slots(serviceId:string,date:string){return this.db.timeSlot.findMany({where:{serviceId,date:new Date(date),status:SlotStatus.ACTIVE,service:{status:'ACTIVE'},availability:{status:AvailabilityStatus.PUBLISHED},startAt:{gt:new Date()}},orderBy:{startAt:'asc'}}).then(x=>x.filter(s=>s.bookedCount<s.capacity))}
 private buildSlots(date:string,startTime:string,endTime:string,duration:number){
   if(!/^\d{2}:\d{2}$/.test(startTime)||!/^\d{2}:\d{2}$/.test(endTime)||duration<=0)throw new BadRequestException('Use HH:mm times and a positive slot duration');
   const start=new Date(`${date}T${startTime}:00+03:00`);const end=new Date(`${date}T${endTime}:00+03:00`);
   if(Number.isNaN(start.valueOf())||end<=start)throw new BadRequestException('End time must be after start time');
   const slots:{startAt:Date;endAt:Date}[]=[];for(let cursor=start.valueOf();cursor<end.valueOf();cursor+=duration*60000){const slotEnd=cursor+duration*60000;if(slotEnd>end.valueOf())throw new BadRequestException('Time range must divide evenly into slot duration');slots.push({startAt:new Date(cursor),endAt:new Date(slotEnd)});}return slots;
 }
 previewAvailability(input:{date:string;startTime:string;endTime:string;slotDuration:number;capacity:number}){if(input.capacity<1)throw new BadRequestException('Capacity must be at least one');return this.buildSlots(input.date,input.startTime,input.endTime,input.slotDuration)}
 async createAvailability(adminId:string,input:{serviceId:string;date:string;startTime:string;endTime:string;slotDuration:number;capacity:number;publish:boolean}){const service=await this.db.service.findUnique({where:{id:input.serviceId}});if(!service)throw new NotFoundException('Service not found');if(service.status!==ServiceStatus.ACTIVE)throw new BadRequestException('Only active services can receive availability');const slots=this.previewAvailability(input);return this.db.$transaction(tx=>tx.availability.create({data:{serviceId:input.serviceId,date:new Date(input.date),startTime:input.startTime,endTime:input.endTime,slotDuration:input.slotDuration,capacity:input.capacity,status:input.publish?AvailabilityStatus.PUBLISHED:AvailabilityStatus.DRAFT,createdById:adminId,slots:{create:slots.map(slot=>({...slot,serviceId:input.serviceId,date:new Date(input.date),capacity:input.capacity}))}},include:{slots:true,service:true}}))}
 private bulkDates(input:BulkAvailabilityInput){this.previewAvailability({date:input.startDate,startTime:input.startTime,endTime:input.endTime,slotDuration:input.slotDuration,capacity:input.capacity});const start=new Date(`${input.startDate}T00:00:00.000Z`);const end=new Date(`${input.endDate}T00:00:00.000Z`);if(Number.isNaN(start.valueOf())||Number.isNaN(end.valueOf())||end<start)throw new BadRequestException('End date must be on or after start date');const weekdays=new Set(input.weekdays);if(!weekdays.size)throw new BadRequestException('Select at least one weekday');const dates:string[]=[];for(let current=start.valueOf();current<=end.valueOf();current+=86400000){const date=new Date(current);if(weekdays.has(date.getUTCDay()))dates.push(date.toISOString().slice(0,10));if(dates.length>366)throw new BadRequestException('Bulk availability is limited to 366 matching days')};if(!dates.length)throw new BadRequestException('No dates match the selected weekdays');return dates}
 private async bulkConflicts(database:PrismaService|Prisma.TransactionClient,input:BulkAvailabilityInput,dates:string[]){const existing=await database.availability.findMany({where:{serviceId:input.serviceId,date:{in:dates.map(date=>new Date(date))},status:{not:AvailabilityStatus.ARCHIVED}},select:{date:true,startTime:true,endTime:true}});return [...new Set(existing.filter(item=>item.startTime<input.endTime&&item.endTime>input.startTime).map(item=>item.date.toISOString().slice(0,10)))]}
 async previewBulkAvailability(input:BulkAvailabilityInput){const service=await this.db.service.findUnique({where:{id:input.serviceId}});if(!service)throw new NotFoundException('Service not found');if(service.status!==ServiceStatus.ACTIVE)throw new BadRequestException('Only active services can receive availability');const dates=this.bulkDates(input);const conflicts=await this.bulkConflicts(this.db,input,dates);const slots=this.previewAvailability({date:input.startDate,startTime:input.startTime,endTime:input.endTime,slotDuration:input.slotDuration,capacity:input.capacity});return {matchingDates:dates,creatableDates:dates.filter(date=>!conflicts.includes(date)),skipped:conflicts.map(date=>({date,reason:'Overlaps existing availability for this service'})),slotsPerDay:slots.length,appointmentsPerDay:slots.length*input.capacity}}
 async createBulkAvailability(adminId:string,input:BulkAvailabilityInput){const preview=await this.previewBulkAvailability(input);return this.db.$transaction(async tx=>{const conflicts=await this.bulkConflicts(tx,input,preview.creatableDates);const dates=preview.creatableDates.filter(date=>!conflicts.includes(date));const slots=this.previewAvailability({date:input.startDate,startTime:input.startTime,endTime:input.endTime,slotDuration:input.slotDuration,capacity:input.capacity});await Promise.all(dates.map(date=>tx.availability.create({data:{serviceId:input.serviceId,date:new Date(date),startTime:input.startTime,endTime:input.endTime,slotDuration:input.slotDuration,capacity:input.capacity,status:input.publish?AvailabilityStatus.PUBLISHED:AvailabilityStatus.DRAFT,createdById:adminId,slots:{create:slots.map(slot=>({...slot,serviceId:input.serviceId,date:new Date(date),capacity:input.capacity}))}}})));const skipped=[...preview.skipped,...conflicts.map(date=>({date,reason:'Became unavailable while publishing'}))];return {createdDates:dates,skipped,slotsPerDay:slots.length,appointmentsPerDay:slots.length*input.capacity}},transactionOptions)}
 async adminAvailability(serviceId?:string,date?:string){return this.db.availability.findMany({where:{...(serviceId?{serviceId}:{}),...(date?{date:new Date(date)}:{})},include:{service:true,slots:true},orderBy:[{date:'asc'},{startTime:'asc'}]})}
 async setSlotBlocked(id:string,blocked:boolean){const slot=await this.db.timeSlot.findUnique({where:{id}});if(!slot)throw new NotFoundException('Slot not found');return this.db.timeSlot.update({where:{id},data:{status:blocked?SlotStatus.BLOCKED:SlotStatus.ACTIVE}})}
 async adminBookings(status?:BookingStatus,serviceId?:string){return this.db.booking.findMany({where:{...(status?{status}:{}),...(serviceId?{serviceId}:{})},include:{client:true,service:true,slot:true},orderBy:{createdAt:'desc'}})}
 async updateBookingStatus(id:string,status:BookingStatus){const booking=await this.db.booking.findUnique({where:{id}});if(!booking)throw new NotFoundException('Booking not found');return this.db.booking.update({where:{id},data:{status,completedAt:status===BookingStatus.COMPLETED?new Date():undefined,cancelledAt:status===BookingStatus.CANCELLED?new Date():undefined}})}
 async adminClients(search?:string){return this.db.client.findMany({where:search?{OR:[{fullName:{contains:search,mode:'insensitive'}},{email:{contains:search,mode:'insensitive'}},{phone:{contains:search,mode:'insensitive'}}]}:{},include:{_count:{select:{bookings:true}}},orderBy:{fullName:'asc'}})}
 async report(){const [total,confirmed,cancelled,completed,slots]=await Promise.all([this.db.booking.count(),this.db.booking.count({where:{status:BookingStatus.CONFIRMED}}),this.db.booking.count({where:{status:BookingStatus.CANCELLED}}),this.db.booking.count({where:{status:BookingStatus.COMPLETED}}),this.db.timeSlot.aggregate({_sum:{capacity:true,bookedCount:true}})]);return {bookings:{total,confirmed,cancelled,completed},utilization:slots._sum.capacity?Math.round(((slots._sum.bookedCount||0)/slots._sum.capacity)*100):0,capacity:{total:slots._sum.capacity||0,reserved:slots._sum.bookedCount||0}}}
 private tokenHash(token:string){return crypto.createHash('sha256').update(token).digest('hex')}
 private async managedBooking(token:string){const booking=await this.db.booking.findFirst({where:{manageTokenHash:this.tokenHash(token),manageTokenExpiresAt:{gt:new Date()}},include:{service:true,slot:true,client:true}});if(!booking)throw new NotFoundException('This booking link is invalid or has expired');return booking}
 async getManagedBooking(token:string){const booking=await this.managedBooking(token);return {reference:booking.bookingReference,status:booking.status,serviceId:booking.serviceId,service:booking.service.name,startAt:booking.slot.startAt,endAt:booking.slot.endAt,location:'Coach Rickie Performance Studio, Lugogo Bypass, Kampala'} }
 private assertClientChangeAllowed(startAt:Date){if(startAt.valueOf()-Date.now()<24*60*60*1000)throw new BadRequestException('Client changes close 24 hours before the session')}
 async cancelManagedBooking(token:string){const managed=await this.managedBooking(token);this.assertClientChangeAllowed(managed.slot.startAt);return this.db.$transaction(async tx=>{const booking=await tx.booking.findUnique({where:{id:managed.id},include:{slot:true}});if(!booking||booking.status!==BookingStatus.CONFIRMED)throw new BadRequestException('Only confirmed bookings can be cancelled');this.assertClientChangeAllowed(booking.slot.startAt);const locked=await tx.$queryRaw<{id:string;bookedCount:number}[]>`SELECT id, "bookedCount" FROM "TimeSlot" WHERE id=${booking.slotId} FOR UPDATE`;if(!locked[0])throw new NotFoundException('Original slot not found');const cancelled=await tx.booking.update({where:{id:booking.id},data:{status:BookingStatus.CANCELLED,cancelledAt:new Date()}});await tx.timeSlot.update({where:{id:booking.slotId},data:{bookedCount:{decrement:1}}});await tx.notification.create({data:{bookingId:booking.id,recipient:managed.client.email,type:'BOOKING_CANCELLED'}});return cancelled},transactionOptions)}
 async rescheduleManagedBooking(token:string,newSlotId:string){const managed=await this.managedBooking(token);this.assertClientChangeAllowed(managed.slot.startAt);if(newSlotId===managed.slotId)throw new BadRequestException('Choose a different time slot');return this.db.$transaction(async tx=>{const booking=await tx.booking.findUnique({where:{id:managed.id},include:{slot:true}});if(!booking||booking.status!==BookingStatus.CONFIRMED)throw new BadRequestException('Only confirmed bookings can be rescheduled');this.assertClientChangeAllowed(booking.slot.startAt);const slots=await tx.$queryRaw<{id:string;serviceId:string;capacity:number;bookedCount:number;status:SlotStatus;startAt:Date;availabilityId:string}[]>`SELECT id, "serviceId", capacity, "bookedCount", status, "startAt", "availabilityId" FROM "TimeSlot" WHERE id IN (${booking.slotId}, ${newSlotId}) ORDER BY id FOR UPDATE`;const target=slots.find(slot=>slot.id===newSlotId);if(!target||target.serviceId!==booking.serviceId||target.status!==SlotStatus.ACTIVE||target.startAt<=new Date()||target.bookedCount>=target.capacity)throw new ConflictException('The selected slot is no longer available');const availability=await tx.availability.findUnique({where:{id:target.availabilityId}});if(availability?.status!==AvailabilityStatus.PUBLISHED)throw new ConflictException('The selected slot is not published');await tx.timeSlot.update({where:{id:booking.slotId},data:{bookedCount:{decrement:1}}});await tx.timeSlot.update({where:{id:newSlotId},data:{bookedCount:{increment:1}}});const updated=await tx.booking.update({where:{id:booking.id},data:{slotId:newSlotId}});await tx.notification.create({data:{bookingId:booking.id,recipient:managed.client.email,type:'BOOKING_RESCHEDULED'}});return updated},transactionOptions)}
 async book(input:{serviceId:string;slotId:string;fullName:string;email:string;phone:string}){const now=new Date();const email=input.email.trim().toLowerCase();return this.db.$transaction(async tx=>{const slots=await tx.$queryRaw<{id:string;capacity:number;bookedCount:number;serviceId:string;status:SlotStatus;startAt:Date}[]>`SELECT * FROM "TimeSlot" WHERE id=${input.slotId} FOR UPDATE`;const slot=slots[0];if(!slot||slot.serviceId!==input.serviceId||slot.status!==SlotStatus.ACTIVE||slot.startAt<=now||slot.bookedCount>=slot.capacity)throw new ConflictException('This slot is no longer available'); const svc=await tx.service.findFirst({where:{id:input.serviceId,status:'ACTIVE'}});if(!svc)throw new BadRequestException('Service is unavailable');const client=await tx.client.upsert({where:{email},update:{fullName:input.fullName,phone:input.phone},create:{fullName:input.fullName,email,phone:input.phone}});const reference=`CR-${now.toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomInt(10000,100000)}`;const token=crypto.randomBytes(32).toString('hex');const booking=await tx.booking.create({data:{bookingReference:reference,clientId:client.id,serviceId:svc.id,slotId:slot.id,manageTokenHash:crypto.createHash('sha256').update(token).digest('hex'),manageTokenExpiresAt:new Date(now.getTime()+1000*60*60*24*30)},include:{client:true,service:true,slot:true}});await tx.timeSlot.update({where:{id:slot.id},data:{bookedCount:{increment:1}}});await tx.notification.create({data:{bookingId:booking.id,recipient:client.email,type:'BOOKING_CONFIRMED'}});return {...booking,manageToken:token}},transactionOptions)}
}
