import { Body,Controller,Delete,Get,Param,Patch,Post,Query,Req,UseGuards } from '@nestjs/common'; import { ArrayNotEmpty, IsArray, IsBoolean, IsEmail, IsEnum, IsInt, IsNotEmpty, IsOptional, IsString, Matches, Max, Min, MinLength } from 'class-validator'; import { BookingStatus, ServiceStatus } from '@prisma/client'; import { SchedulingService } from './scheduling.service'; import { JwtAuthGuard } from '../auth/jwt-auth.guard';
class BookingDto {@IsString() @IsNotEmpty() serviceId!:string;@IsString() @IsNotEmpty() slotId!:string;@IsString() @IsNotEmpty() fullName!:string;@IsEmail() email!:string;@IsString() @IsNotEmpty() phone!:string}
class ServiceDto {@IsString() @MinLength(2) name!:string;@IsString() @MinLength(5) description!:string;@IsInt() @Min(5) durationMinutes!:number;@IsInt() @Min(0) priceMinor!:number;@IsOptional() @IsEnum(ServiceStatus) status?:ServiceStatus}
class UpdateServiceDto {@IsOptional() @IsString() @MinLength(2) name?:string;@IsOptional() @IsString() @MinLength(5) description?:string;@IsOptional() @IsInt() @Min(5) durationMinutes?:number;@IsOptional() @IsInt() @Min(0) priceMinor?:number;@IsOptional() @IsEnum(ServiceStatus) status?:ServiceStatus}
class AvailabilityDto {@IsString() serviceId!:string;@Matches(/^\d{4}-\d{2}-\d{2}$/) date!:string;@Matches(/^\d{2}:\d{2}$/) startTime!:string;@Matches(/^\d{2}:\d{2}$/) endTime!:string;@IsInt() @Min(5) slotDuration!:number;@IsInt() @Min(1) capacity!:number;@IsBoolean() publish!:boolean}
class BulkAvailabilityDto {@IsString() serviceId!:string;@Matches(/^\d{4}-\d{2}-\d{2}$/) startDate!:string;@Matches(/^\d{4}-\d{2}-\d{2}$/) endDate!:string;@IsArray() @ArrayNotEmpty() @IsInt({each:true}) @Min(0,{each:true}) @Max(6,{each:true}) weekdays!:number[];@Matches(/^\d{2}:\d{2}$/) startTime!:string;@Matches(/^\d{2}:\d{2}$/) endTime!:string;@IsInt() @Min(5) slotDuration!:number;@IsInt() @Min(1) capacity!:number;@IsBoolean() publish!:boolean}
class RescheduleDto {@IsString() @IsNotEmpty() slotId!:string}
class BookingStatusDto {@IsEnum(BookingStatus) status!:BookingStatus}
@Controller('services') export class ServicesController {constructor(private s:SchedulingService){}@Get() list(){return this.s.services()}@Get(':id/available-dates') dates(@Param('id')id:string){return this.s.dates(id)}@Get(':id/slots')slots(@Param('id')id:string,@Query('date')date:string){return this.s.slots(id,date)}}
@Controller('bookings') export class BookingController {constructor(private s:SchedulingService){}@Post() create(@Body()b:BookingDto){return this.s.book(b)}}
@Controller('manage-booking') export class ManageBookingController {constructor(private s:SchedulingService){}@Get(':token')get(@Param('token')token:string){return this.s.getManagedBooking(token)}@Post(':token/cancel')cancel(@Param('token')token:string){return this.s.cancelManagedBooking(token)}@Post(':token/reschedule')reschedule(@Param('token')token:string,@Body()body:RescheduleDto){return this.s.rescheduleManagedBooking(token,body.slotId)}}
@UseGuards(JwtAuthGuard)
@Controller('admin/services') export class AdminServicesController {constructor(private s:SchedulingService){}@Get()list(){return this.s.adminServices()}@Post()create(@Body()body:ServiceDto){return this.s.createService(body)}@Patch(':id')update(@Param('id')id:string,@Body()body:UpdateServiceDto){return this.s.updateService(id,body)}@Delete(':id')remove(@Param('id')id:string){return this.s.archiveService(id)}}
@UseGuards(JwtAuthGuard)
@Controller('admin/availability') export class AvailabilityController {constructor(private s:SchedulingService){}@Get()list(@Query('serviceId')serviceId?:string,@Query('date')date?:string){return this.s.adminAvailability(serviceId,date)}@Post('preview')preview(@Body()body:AvailabilityDto){return this.s.previewAvailability(body)}@Post('bulk-preview')bulkPreview(@Body()body:BulkAvailabilityDto){return this.s.previewBulkAvailability(body)}@Post('bulk')bulkCreate(@Req()request:{admin:{id:string}},@Body()body:BulkAvailabilityDto){return this.s.createBulkAvailability(request.admin.id,body)}@Post()create(@Req()request:{admin:{id:string}},@Body()body:AvailabilityDto){return this.s.createAvailability(request.admin.id,body)}@Patch('slots/:id/block')block(@Param('id')id:string,@Body()body:{blocked:boolean}){return this.s.setSlotBlocked(id,body.blocked)}}
@UseGuards(JwtAuthGuard)
@Controller('admin') export class AdminOperationsController {constructor(private s:SchedulingService){}@Get('bookings')bookings(@Query('status')status?:BookingStatus,@Query('serviceId')serviceId?:string){return this.s.adminBookings(status,serviceId)}@Patch('bookings/:id/status')bookingStatus(@Param('id')id:string,@Body()body:BookingStatusDto){return this.s.updateBookingStatus(id,body.status)}@Get('clients')clients(@Query('search')search?:string){return this.s.adminClients(search)}@Get('reports')report(){return this.s.report()}}
