'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiUrl as api } from '../lib/api-url';

type Service = { id: string; name: string; description: string; durationMinutes: number; priceMinor: number };
const serviceImages: Record<string, string> = { 'Personal Training': '/images/personal-training.jfif', 'Public Training': '/images/public-training.jfif', 'Public/Group Training': '/images/public-training.jfif', 'Smash Room': '/images/smash-room-logo.jpg', 'Team Building': '/images/team-building.jfif' };

export default function Home() {
  const [services, setServices] = useState<Service[]>([]);
  useEffect(() => { fetch(`${api}/services`).then((response) => response.json()).then(setServices).catch(() => setServices([])); }, []);

  return <>
    <header className="site-header"><div className="container site-header__content"><Link className="brand" href="/">COACH RICKIE<span>.</span></Link><nav className="site-header__actions" aria-label="Primary navigation"><Link className="header-link" href="/contact">Contact</Link><Link className="button cut-corner-sm" href="#services">Book session</Link></nav></div></header>
    <main>
      <section className="hero bg-grid-pattern"><div className="container hero__content"><div className="eyebrow">Kampala athletic performance & recovery</div><h1>Forge strength<br /><span className="accent">Unleash power</span><br />No excuses.</h1><p className="text-secondary">Elite coaching, group conditioning, recovery protocols, and the city&apos;s premier Smash Room—booked against live capacity-aware availability.</p><div className="hero__actions"><Link className="button cut-corner" href="#services">Book a session</Link><a className="button button--secondary cut-corner" href="#services">Explore services</a></div></div></section>
      <section id="services" className="section"><div className="container"><div className="eyebrow">Training disciplines</div><h2 className="section-title">What we offer</h2><div className="service-grid">{services.map((service) => <Link className="service-card cut-corner" key={service.id} href={`/book?serviceId=${service.id}`}>{serviceImages[service.name] && <div className={`service-card__image ${service.name === 'Smash Room' ? 'service-card__image--logo' : ''}`}><img src={serviceImages[service.name]} alt="" /></div>}<div><div className="eyebrow">{service.durationMinutes} min</div><h3>{service.name}</h3><p className="text-secondary">{service.description}</p></div><div className="service-card__price">{service.priceMinor === 0 ? 'Included in plan' : `UGX ${service.priceMinor.toLocaleString()} / session`}</div></Link>)}</div>{services.length === 0 && <p className="muted">Services will appear when the API is running and seeded.</p>}</div></section>
      <section className="section split-section"><div className="container"><div className="eyebrow">The protocol</div><h2 className="section-title">How it works</h2><div className="protocol-grid"><article className="protocol-card cut-corner"><div className="protocol-card__number">01</div><h3>Pick your discipline</h3><p className="text-secondary">Choose focused personal coaching, group conditioning, recovery, or a Smash Room session.</p></article><article className="protocol-card cut-corner"><div className="protocol-card__number">02</div><h3>Choose your time</h3><p className="text-secondary">Select a future slot from live published availability with capacity checked by the booking engine.</p></article><article className="protocol-card cut-corner"><div className="protocol-card__number">03</div><h3>Show up & execute</h3><p className="text-secondary">Arrive ready to train at the Lugogo Bypass studio—coach-led, prepared, and on schedule.</p></article></div></div></section>
      <section id="smash-room" className="section"><div className="container feature-split"><div><div className="eyebrow">Extreme stress release</div><h2 className="section-title">The Smash Room</h2><p className="text-secondary">A controlled, coach-supervised environment for powerful release. Protective equipment and safe impact tools are prepared before every booked session.</p><aside className="service-disclaimer" role="note"><strong>Important disclaimer</strong><p>Rage Room does not claim to be a mental health or medical facility. We do not treat, diagnose, or provide medical therapy of any kind. We are classified as entertainment only. If you feel that you have mental or medical issues that need treatment, please see a licensed physician or obtain a referral. Thank you.</p></aside><ul className="feature-list"><li>Protective equipment supplied</li><li>Dedicated impact zones</li><li>Private, capacity-controlled bookings</li></ul><Link className="button cut-corner" href="#services">Book Smash Room</Link></div><aside className="feature-stamp cut-corner"><span>SMR</span><small>Controlled. Safe. Cathartic.</small></aside></div></section>
      <section id="coach" className="section split-section"><div className="container feature-split"><aside className="feature-stamp feature-stamp--quiet cut-corner"><span>CR</span><small>Coach-led performance</small></aside><div><div className="eyebrow">Kampala HQ</div><h2 className="section-title">Built around your goals</h2><p className="text-secondary">Coach Rickie combines athletic performance, practical conditioning, and recovery planning in one disciplined space. Every reservation is checked against the live schedule before it is confirmed.</p><p className="text-secondary">Lugogo Bypass, Kampala · Free parking · Arrive 10 minutes early.</p></div></div></section>
      <section id="schedule" className="section"><div className="container"><div className="eyebrow">Live schedule</div><h2 className="section-title">Find your next session</h2><p className="text-secondary schedule-intro">Availability changes as athletes book, cancel, and reschedule. Select a discipline to see only future slots with remaining capacity.</p><div className="service-grid">{services.map(service=><Link className="service-card cut-corner" key={`schedule-${service.id}`} href={`/book?serviceId=${service.id}`}><div><div className="eyebrow">Live availability</div><h3>{service.name}</h3><p className="text-secondary">View published dates and capacity-aware session times.</p></div><div className="service-card__price">View timetable →</div></Link>)}</div></div></section>
      <section className="section"><div className="container"><div className="cta-band cut-corner"><div className="eyebrow">Coach Rickie performance studio · Lugogo Bypass</div><h2>Built for people who show up.</h2><p className="text-secondary">Your booking is backed by real availability, capacity controls, and a secure confirmation link for changes when plans move.</p><div className="hero__actions"><Link className="button cut-corner" href="#services">Find a session</Link></div></div></div></section>
    </main>
  </>;
}
